#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : BCD_modulo_3.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Oct 20 18:58:47 +0330 2020
# SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: BCD_modulo_3.sh [-help]
# usage: BCD_modulo_3.sh [-lib_map_path]
# usage: BCD_modulo_3.sh [-noclean_files]
# usage: BCD_modulo_3.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'BCD_modulo_3.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib util_vector_logic_v2_0_1)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "BCD_modulo_3.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/BCD_modulo_3/sim/BCD_modulo_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k \
    "$ref_dir/../../../../project_2.srcs/sources_1/bd/BCD_modulo_3/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_2/sim/BCD_modulo_3_util_vector_logic_0_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_3/sim/BCD_modulo_3_util_vector_logic_0_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_4/sim/BCD_modulo_3_util_vector_logic_0_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_5/sim/BCD_modulo_3_util_vector_logic_0_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_1/sim/BCD_modulo_3_util_vector_logic_4_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_2/sim/BCD_modulo_3_util_vector_logic_4_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_3/sim/BCD_modulo_3_util_vector_logic_4_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_4/sim/BCD_modulo_3_util_vector_logic_4_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_5/sim/BCD_modulo_3_util_vector_logic_4_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_6/sim/BCD_modulo_3_util_vector_logic_4_6.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_0/sim/BCD_modulo_3_util_vector_logic_10_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_1/sim/BCD_modulo_3_util_vector_logic_10_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_0/sim/BCD_modulo_3_util_vector_logic_12_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_0/sim/BCD_modulo_3_util_vector_logic_13_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_1/sim/BCD_modulo_3_util_vector_logic_13_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_2/sim/BCD_modulo_3_util_vector_logic_13_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_3/sim/BCD_modulo_3_util_vector_logic_13_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_0/sim/BCD_modulo_3_util_vector_logic_14_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_0/sim/BCD_modulo_3_util_vector_logic_15_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_4/sim/BCD_modulo_3_util_vector_logic_13_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_1/sim/BCD_modulo_3_util_vector_logic_14_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_1/sim/BCD_modulo_3_util_vector_logic_15_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_0/sim/BCD_modulo_3_util_vector_logic_22_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_1/sim/BCD_modulo_3_util_vector_logic_22_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_6/sim/BCD_modulo_3_util_vector_logic_0_6.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_0/sim/BCD_modulo_3_util_vector_logic_1_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_0/sim/BCD_modulo_3_util_vector_logic_2_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_0/sim/BCD_modulo_3_util_vector_logic_3_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_7/sim/BCD_modulo_3_util_vector_logic_4_7.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_0/sim/BCD_modulo_3_util_vector_logic_5_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_0/sim/BCD_modulo_3_util_vector_logic_6_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_0/sim/BCD_modulo_3_util_vector_logic_7_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_0/sim/BCD_modulo_3_util_vector_logic_8_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_0/sim/BCD_modulo_3_util_vector_logic_9_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_2/sim/BCD_modulo_3_util_vector_logic_10_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_0/sim/BCD_modulo_3_util_vector_logic_11_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_1/sim/BCD_modulo_3_util_vector_logic_12_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_5/sim/BCD_modulo_3_util_vector_logic_13_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_2/sim/BCD_modulo_3_util_vector_logic_14_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_2/sim/BCD_modulo_3_util_vector_logic_15_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_0/sim/BCD_modulo_3_util_vector_logic_16_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_0/sim/BCD_modulo_3_util_vector_logic_17_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_0/sim/BCD_modulo_3_util_vector_logic_18_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_0/sim/BCD_modulo_3_util_vector_logic_19_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_0/sim/BCD_modulo_3_util_vector_logic_20_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_0/sim/BCD_modulo_3_util_vector_logic_21_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_2/sim/BCD_modulo_3_util_vector_logic_22_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_0/sim/BCD_modulo_3_util_vector_logic_23_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_7/sim/BCD_modulo_3_util_vector_logic_0_7.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_8/sim/BCD_modulo_3_util_vector_logic_0_8.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_9/sim/BCD_modulo_3_util_vector_logic_0_9.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_10/sim/BCD_modulo_3_util_vector_logic_0_10.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_8/sim/BCD_modulo_3_util_vector_logic_4_8.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_9/sim/BCD_modulo_3_util_vector_logic_4_9.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_10/sim/BCD_modulo_3_util_vector_logic_4_10.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_11/sim/BCD_modulo_3_util_vector_logic_4_11.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_12/sim/BCD_modulo_3_util_vector_logic_4_12.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_13/sim/BCD_modulo_3_util_vector_logic_4_13.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_14/sim/BCD_modulo_3_util_vector_logic_4_14.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_15/sim/BCD_modulo_3_util_vector_logic_4_15.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_16/sim/BCD_modulo_3_util_vector_logic_4_16.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_7/sim/BCD_modulo_3_util_vector_logic_13_7.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_8/sim/BCD_modulo_3_util_vector_logic_13_8.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_17/sim/BCD_modulo_3_util_vector_logic_4_17.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_1/sim/BCD_modulo_3_util_vector_logic_5_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_1/sim/BCD_modulo_3_util_vector_logic_7_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_3/sim/BCD_modulo_3_util_vector_logic_15_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_1/sim/BCD_modulo_3_util_vector_logic_16_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_1/sim/BCD_modulo_3_util_vector_logic_17_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_4/sim/BCD_modulo_3_util_vector_logic_15_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_2/sim/BCD_modulo_3_util_vector_logic_16_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_2/sim/BCD_modulo_3_util_vector_logic_17_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_9/sim/BCD_modulo_3_util_vector_logic_13_9.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_3/sim/BCD_modulo_3_util_vector_logic_14_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_11/sim/BCD_modulo_3_util_vector_logic_0_11.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_1/sim/BCD_modulo_3_util_vector_logic_1_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_1/sim/BCD_modulo_3_util_vector_logic_2_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_1/sim/BCD_modulo_3_util_vector_logic_3_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_18/sim/BCD_modulo_3_util_vector_logic_4_18.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_2/sim/BCD_modulo_3_util_vector_logic_5_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_1/sim/BCD_modulo_3_util_vector_logic_6_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_2/sim/BCD_modulo_3_util_vector_logic_7_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_1/sim/BCD_modulo_3_util_vector_logic_8_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_1/sim/BCD_modulo_3_util_vector_logic_9_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_3/sim/BCD_modulo_3_util_vector_logic_10_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_1/sim/BCD_modulo_3_util_vector_logic_11_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_2/sim/BCD_modulo_3_util_vector_logic_12_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_10/sim/BCD_modulo_3_util_vector_logic_13_10.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_4/sim/BCD_modulo_3_util_vector_logic_14_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_5/sim/BCD_modulo_3_util_vector_logic_15_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_3/sim/BCD_modulo_3_util_vector_logic_16_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_3/sim/BCD_modulo_3_util_vector_logic_17_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_1/sim/BCD_modulo_3_util_vector_logic_18_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_1/sim/BCD_modulo_3_util_vector_logic_19_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_1/sim/BCD_modulo_3_util_vector_logic_20_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_1/sim/BCD_modulo_3_util_vector_logic_21_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_3/sim/BCD_modulo_3_util_vector_logic_22_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_1/sim/BCD_modulo_3_util_vector_logic_23_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_12/sim/BCD_modulo_3_util_vector_logic_0_12.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_2/sim/BCD_modulo_3_util_vector_logic_1_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_2/sim/BCD_modulo_3_util_vector_logic_2_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_2/sim/BCD_modulo_3_util_vector_logic_3_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_19/sim/BCD_modulo_3_util_vector_logic_4_19.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_3/sim/BCD_modulo_3_util_vector_logic_5_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_2/sim/BCD_modulo_3_util_vector_logic_6_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_3/sim/BCD_modulo_3_util_vector_logic_7_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_2/sim/BCD_modulo_3_util_vector_logic_8_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_2/sim/BCD_modulo_3_util_vector_logic_9_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_4/sim/BCD_modulo_3_util_vector_logic_10_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_2/sim/BCD_modulo_3_util_vector_logic_11_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_3/sim/BCD_modulo_3_util_vector_logic_12_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_11/sim/BCD_modulo_3_util_vector_logic_13_11.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_5/sim/BCD_modulo_3_util_vector_logic_14_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_6/sim/BCD_modulo_3_util_vector_logic_15_6.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_4/sim/BCD_modulo_3_util_vector_logic_16_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_4/sim/BCD_modulo_3_util_vector_logic_17_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_2/sim/BCD_modulo_3_util_vector_logic_18_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_2/sim/BCD_modulo_3_util_vector_logic_19_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_2/sim/BCD_modulo_3_util_vector_logic_20_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_2/sim/BCD_modulo_3_util_vector_logic_21_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_4/sim/BCD_modulo_3_util_vector_logic_22_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_2/sim/BCD_modulo_3_util_vector_logic_23_2.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_13/sim/BCD_modulo_3_util_vector_logic_0_13.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_3/sim/BCD_modulo_3_util_vector_logic_1_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_3/sim/BCD_modulo_3_util_vector_logic_2_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_3/sim/BCD_modulo_3_util_vector_logic_3_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_20/sim/BCD_modulo_3_util_vector_logic_4_20.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_4/sim/BCD_modulo_3_util_vector_logic_5_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_3/sim/BCD_modulo_3_util_vector_logic_6_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_4/sim/BCD_modulo_3_util_vector_logic_7_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_3/sim/BCD_modulo_3_util_vector_logic_8_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_3/sim/BCD_modulo_3_util_vector_logic_9_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_5/sim/BCD_modulo_3_util_vector_logic_10_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_3/sim/BCD_modulo_3_util_vector_logic_11_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_4/sim/BCD_modulo_3_util_vector_logic_12_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_12/sim/BCD_modulo_3_util_vector_logic_13_12.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_6/sim/BCD_modulo_3_util_vector_logic_14_6.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_7/sim/BCD_modulo_3_util_vector_logic_15_7.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_5/sim/BCD_modulo_3_util_vector_logic_16_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_5/sim/BCD_modulo_3_util_vector_logic_17_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_3/sim/BCD_modulo_3_util_vector_logic_18_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_3/sim/BCD_modulo_3_util_vector_logic_19_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_3/sim/BCD_modulo_3_util_vector_logic_20_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_3/sim/BCD_modulo_3_util_vector_logic_21_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_5/sim/BCD_modulo_3_util_vector_logic_22_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_3/sim/BCD_modulo_3_util_vector_logic_23_3.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_24_0/sim/BCD_modulo_3_util_vector_logic_24_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_25_0/sim/BCD_modulo_3_util_vector_logic_25_0.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_14/sim/BCD_modulo_3_util_vector_logic_0_14.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_4/sim/BCD_modulo_3_util_vector_logic_1_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_4/sim/BCD_modulo_3_util_vector_logic_2_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_4/sim/BCD_modulo_3_util_vector_logic_3_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_21/sim/BCD_modulo_3_util_vector_logic_4_21.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_5/sim/BCD_modulo_3_util_vector_logic_5_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_4/sim/BCD_modulo_3_util_vector_logic_6_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_5/sim/BCD_modulo_3_util_vector_logic_7_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_4/sim/BCD_modulo_3_util_vector_logic_8_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_4/sim/BCD_modulo_3_util_vector_logic_9_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_6/sim/BCD_modulo_3_util_vector_logic_10_6.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_4/sim/BCD_modulo_3_util_vector_logic_11_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_5/sim/BCD_modulo_3_util_vector_logic_12_5.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_13/sim/BCD_modulo_3_util_vector_logic_13_13.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_7/sim/BCD_modulo_3_util_vector_logic_14_7.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_8/sim/BCD_modulo_3_util_vector_logic_15_8.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_6/sim/BCD_modulo_3_util_vector_logic_16_6.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_6/sim/BCD_modulo_3_util_vector_logic_17_6.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_4/sim/BCD_modulo_3_util_vector_logic_18_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_4/sim/BCD_modulo_3_util_vector_logic_19_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_4/sim/BCD_modulo_3_util_vector_logic_20_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_4/sim/BCD_modulo_3_util_vector_logic_21_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_6/sim/BCD_modulo_3_util_vector_logic_22_6.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_4/sim/BCD_modulo_3_util_vector_logic_23_4.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_24_1/sim/BCD_modulo_3_util_vector_logic_24_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_25_1/sim/BCD_modulo_3_util_vector_logic_25_1.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_15/sim/BCD_modulo_3_util_vector_logic_0_15.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_16/sim/BCD_modulo_3_util_vector_logic_0_16.v" \
    "$ref_dir/../../../bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_17/sim/BCD_modulo_3_util_vector_logic_0_17.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.BCD_modulo_3 xil_defaultlib.glbl -o BCD_modulo_3_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./BCD_modulo_3_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./BCD_modulo_3.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key BCD_modulo_3_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc BCD_modulo_3_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./BCD_modulo_3.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: BCD_modulo_3.sh [-help]\n\
Usage: BCD_modulo_3.sh [-lib_map_path]\n\
Usage: BCD_modulo_3.sh [-reset_run]\n\
Usage: BCD_modulo_3.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
