# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/counter_4/counter_4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4 || ORIG_REF_NAME==counter_4} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_33/counter_4_util_vector_logic_0_33.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_33 || ORIG_REF_NAME==counter_4_util_vector_logic_0_33} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_30/counter_4_util_vector_logic_2_30.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_30 || ORIG_REF_NAME==counter_4_util_vector_logic_2_30} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_34/counter_4_util_vector_logic_0_34.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_34 || ORIG_REF_NAME==counter_4_util_vector_logic_0_34} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_31/counter_4_util_vector_logic_2_31.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_31 || ORIG_REF_NAME==counter_4_util_vector_logic_2_31} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_not_0_1/counter_4_not_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_not_0_1 || ORIG_REF_NAME==counter_4_not_0_1} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_35/counter_4_util_vector_logic_0_35.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_35 || ORIG_REF_NAME==counter_4_util_vector_logic_0_35} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_32/counter_4_util_vector_logic_2_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_32 || ORIG_REF_NAME==counter_4_util_vector_logic_2_32} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_36/counter_4_util_vector_logic_0_36.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_36 || ORIG_REF_NAME==counter_4_util_vector_logic_0_36} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_33/counter_4_util_vector_logic_2_33.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_33 || ORIG_REF_NAME==counter_4_util_vector_logic_2_33} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_37/counter_4_util_vector_logic_0_37.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_37 || ORIG_REF_NAME==counter_4_util_vector_logic_0_37} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_34/counter_4_util_vector_logic_2_34.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_34 || ORIG_REF_NAME==counter_4_util_vector_logic_2_34} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_38/counter_4_util_vector_logic_0_38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_38 || ORIG_REF_NAME==counter_4_util_vector_logic_0_38} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_35/counter_4_util_vector_logic_2_35.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_35 || ORIG_REF_NAME==counter_4_util_vector_logic_2_35} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_39/counter_4_util_vector_logic_0_39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_39 || ORIG_REF_NAME==counter_4_util_vector_logic_0_39} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_36/counter_4_util_vector_logic_2_36.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_36 || ORIG_REF_NAME==counter_4_util_vector_logic_2_36} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_40/counter_4_util_vector_logic_0_40.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_40 || ORIG_REF_NAME==counter_4_util_vector_logic_0_40} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_37/counter_4_util_vector_logic_2_37.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_37 || ORIG_REF_NAME==counter_4_util_vector_logic_2_37} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_not_1_1/counter_4_not_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_not_1_1 || ORIG_REF_NAME==counter_4_not_1_1} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_41/counter_4_util_vector_logic_0_41.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_41 || ORIG_REF_NAME==counter_4_util_vector_logic_0_41} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_42/counter_4_util_vector_logic_0_42.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_42 || ORIG_REF_NAME==counter_4_util_vector_logic_0_42} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_43/counter_4_util_vector_logic_0_43.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_43 || ORIG_REF_NAME==counter_4_util_vector_logic_0_43} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_0_0/counter_4_and_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_0_0 || ORIG_REF_NAME==counter_4_and_0_0} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_44/counter_4_util_vector_logic_0_44.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_44 || ORIG_REF_NAME==counter_4_util_vector_logic_0_44} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_38/counter_4_util_vector_logic_2_38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_38 || ORIG_REF_NAME==counter_4_util_vector_logic_2_38} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_45/counter_4_util_vector_logic_0_45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_45 || ORIG_REF_NAME==counter_4_util_vector_logic_0_45} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_39/counter_4_util_vector_logic_2_39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_39 || ORIG_REF_NAME==counter_4_util_vector_logic_2_39} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_not_0_2/counter_4_not_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_not_0_2 || ORIG_REF_NAME==counter_4_not_0_2} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_46/counter_4_util_vector_logic_0_46.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_46 || ORIG_REF_NAME==counter_4_util_vector_logic_0_46} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_40/counter_4_util_vector_logic_2_40.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_40 || ORIG_REF_NAME==counter_4_util_vector_logic_2_40} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_47/counter_4_util_vector_logic_0_47.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_47 || ORIG_REF_NAME==counter_4_util_vector_logic_0_47} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_41/counter_4_util_vector_logic_2_41.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_41 || ORIG_REF_NAME==counter_4_util_vector_logic_2_41} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_48/counter_4_util_vector_logic_0_48.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_48 || ORIG_REF_NAME==counter_4_util_vector_logic_0_48} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_42/counter_4_util_vector_logic_2_42.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_42 || ORIG_REF_NAME==counter_4_util_vector_logic_2_42} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_49/counter_4_util_vector_logic_0_49.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_49 || ORIG_REF_NAME==counter_4_util_vector_logic_0_49} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_43/counter_4_util_vector_logic_2_43.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_43 || ORIG_REF_NAME==counter_4_util_vector_logic_2_43} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_50/counter_4_util_vector_logic_0_50.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_50 || ORIG_REF_NAME==counter_4_util_vector_logic_0_50} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_44/counter_4_util_vector_logic_2_44.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_44 || ORIG_REF_NAME==counter_4_util_vector_logic_2_44} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_51/counter_4_util_vector_logic_0_51.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_51 || ORIG_REF_NAME==counter_4_util_vector_logic_0_51} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_45/counter_4_util_vector_logic_2_45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_45 || ORIG_REF_NAME==counter_4_util_vector_logic_2_45} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_not_1_2/counter_4_not_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_not_1_2 || ORIG_REF_NAME==counter_4_not_1_2} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_0_1/counter_4_and_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_0_1 || ORIG_REF_NAME==counter_4_and_0_1} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_or_0_0/counter_4_or_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_or_0_0 || ORIG_REF_NAME==counter_4_or_0_0} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_52/counter_4_util_vector_logic_0_52.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_52 || ORIG_REF_NAME==counter_4_util_vector_logic_0_52} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_1_0/counter_4_and_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_1_0 || ORIG_REF_NAME==counter_4_and_1_0} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_53/counter_4_util_vector_logic_0_53.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_53 || ORIG_REF_NAME==counter_4_util_vector_logic_0_53} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_46/counter_4_util_vector_logic_2_46.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_46 || ORIG_REF_NAME==counter_4_util_vector_logic_2_46} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_54/counter_4_util_vector_logic_0_54.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_54 || ORIG_REF_NAME==counter_4_util_vector_logic_0_54} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_47/counter_4_util_vector_logic_2_47.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_47 || ORIG_REF_NAME==counter_4_util_vector_logic_2_47} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_not_0_3/counter_4_not_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_not_0_3 || ORIG_REF_NAME==counter_4_not_0_3} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_55/counter_4_util_vector_logic_0_55.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_55 || ORIG_REF_NAME==counter_4_util_vector_logic_0_55} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_48/counter_4_util_vector_logic_2_48.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_48 || ORIG_REF_NAME==counter_4_util_vector_logic_2_48} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_56/counter_4_util_vector_logic_0_56.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_56 || ORIG_REF_NAME==counter_4_util_vector_logic_0_56} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_49/counter_4_util_vector_logic_2_49.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_49 || ORIG_REF_NAME==counter_4_util_vector_logic_2_49} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_57/counter_4_util_vector_logic_0_57.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_57 || ORIG_REF_NAME==counter_4_util_vector_logic_0_57} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_50/counter_4_util_vector_logic_2_50.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_50 || ORIG_REF_NAME==counter_4_util_vector_logic_2_50} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_58/counter_4_util_vector_logic_0_58.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_58 || ORIG_REF_NAME==counter_4_util_vector_logic_0_58} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_51/counter_4_util_vector_logic_2_51.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_51 || ORIG_REF_NAME==counter_4_util_vector_logic_2_51} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_59/counter_4_util_vector_logic_0_59.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_59 || ORIG_REF_NAME==counter_4_util_vector_logic_0_59} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_52/counter_4_util_vector_logic_2_52.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_52 || ORIG_REF_NAME==counter_4_util_vector_logic_2_52} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_60/counter_4_util_vector_logic_0_60.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_60 || ORIG_REF_NAME==counter_4_util_vector_logic_0_60} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_53/counter_4_util_vector_logic_2_53.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_53 || ORIG_REF_NAME==counter_4_util_vector_logic_2_53} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_not_1_3/counter_4_not_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_not_1_3 || ORIG_REF_NAME==counter_4_not_1_3} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_0_2/counter_4_and_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_0_2 || ORIG_REF_NAME==counter_4_and_0_2} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_or_0_1/counter_4_or_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_or_0_1 || ORIG_REF_NAME==counter_4_or_0_1} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_61/counter_4_util_vector_logic_0_61.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_61 || ORIG_REF_NAME==counter_4_util_vector_logic_0_61} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_1_1/counter_4_and_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_1_1 || ORIG_REF_NAME==counter_4_and_1_1} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_62/counter_4_util_vector_logic_0_62.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_62 || ORIG_REF_NAME==counter_4_util_vector_logic_0_62} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_54/counter_4_util_vector_logic_2_54.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_54 || ORIG_REF_NAME==counter_4_util_vector_logic_2_54} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_63/counter_4_util_vector_logic_0_63.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_63 || ORIG_REF_NAME==counter_4_util_vector_logic_0_63} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_55/counter_4_util_vector_logic_2_55.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_55 || ORIG_REF_NAME==counter_4_util_vector_logic_2_55} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_not_0_4/counter_4_not_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_not_0_4 || ORIG_REF_NAME==counter_4_not_0_4} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_64/counter_4_util_vector_logic_0_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_64 || ORIG_REF_NAME==counter_4_util_vector_logic_0_64} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_56/counter_4_util_vector_logic_2_56.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_56 || ORIG_REF_NAME==counter_4_util_vector_logic_2_56} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_65/counter_4_util_vector_logic_0_65.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_65 || ORIG_REF_NAME==counter_4_util_vector_logic_0_65} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_57/counter_4_util_vector_logic_2_57.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_57 || ORIG_REF_NAME==counter_4_util_vector_logic_2_57} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_66/counter_4_util_vector_logic_0_66.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_66 || ORIG_REF_NAME==counter_4_util_vector_logic_0_66} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_58/counter_4_util_vector_logic_2_58.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_58 || ORIG_REF_NAME==counter_4_util_vector_logic_2_58} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_67/counter_4_util_vector_logic_0_67.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_67 || ORIG_REF_NAME==counter_4_util_vector_logic_0_67} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_59/counter_4_util_vector_logic_2_59.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_59 || ORIG_REF_NAME==counter_4_util_vector_logic_2_59} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_68/counter_4_util_vector_logic_0_68.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_68 || ORIG_REF_NAME==counter_4_util_vector_logic_0_68} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_60/counter_4_util_vector_logic_2_60.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_60 || ORIG_REF_NAME==counter_4_util_vector_logic_2_60} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_69/counter_4_util_vector_logic_0_69.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_69 || ORIG_REF_NAME==counter_4_util_vector_logic_0_69} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_2_61/counter_4_util_vector_logic_2_61.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_2_61 || ORIG_REF_NAME==counter_4_util_vector_logic_2_61} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_not_1_4/counter_4_not_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_not_1_4 || ORIG_REF_NAME==counter_4_not_1_4} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_0_3/counter_4_and_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_0_3 || ORIG_REF_NAME==counter_4_and_0_3} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_or_0_2/counter_4_or_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_or_0_2 || ORIG_REF_NAME==counter_4_or_0_2} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_70/counter_4_util_vector_logic_0_70.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_70 || ORIG_REF_NAME==counter_4_util_vector_logic_0_70} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_1_2/counter_4_and_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_1_2 || ORIG_REF_NAME==counter_4_and_1_2} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_71/counter_4_util_vector_logic_0_71.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_71 || ORIG_REF_NAME==counter_4_util_vector_logic_0_71} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_1_0/counter_4_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_1_0 || ORIG_REF_NAME==counter_4_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_72/counter_4_util_vector_logic_0_72.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_72 || ORIG_REF_NAME==counter_4_util_vector_logic_0_72} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_util_vector_logic_0_73/counter_4_util_vector_logic_0_73.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_util_vector_logic_0_73 || ORIG_REF_NAME==counter_4_util_vector_logic_0_73} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_not_0_5/counter_4_not_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_not_0_5 || ORIG_REF_NAME==counter_4_not_0_5} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_0_4/counter_4_and_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_0_4 || ORIG_REF_NAME==counter_4_and_0_4} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_0_5/counter_4_and_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_0_5 || ORIG_REF_NAME==counter_4_and_0_5} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_0_6/counter_4_and_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_0_6 || ORIG_REF_NAME==counter_4_and_0_6} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_or_0_3/counter_4_or_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_or_0_3 || ORIG_REF_NAME==counter_4_or_0_3} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_2_0/counter_4_and_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_2_0 || ORIG_REF_NAME==counter_4_and_2_0} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_2_1/counter_4_and_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_2_1 || ORIG_REF_NAME==counter_4_and_2_1} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_or_1_0/counter_4_or_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_or_1_0 || ORIG_REF_NAME==counter_4_or_1_0} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_0_7/counter_4_and_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_0_7 || ORIG_REF_NAME==counter_4_and_0_7} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_0_8/counter_4_and_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_0_8 || ORIG_REF_NAME==counter_4_and_0_8} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_2_2/counter_4_and_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_2_2 || ORIG_REF_NAME==counter_4_and_2_2} -quiet] -quiet

# IP: bd/counter_4/ip/counter_4_and_4_0/counter_4_and_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_4_and_4_0 || ORIG_REF_NAME==counter_4_and_4_0} -quiet] -quiet

# XDC: bd/counter_4/counter_4_ooc.xdc
