# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/BCD_modulo_3/BCD_modulo_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3 || ORIG_REF_NAME==BCD_modulo_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_2/BCD_modulo_3_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_3/BCD_modulo_3_util_vector_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_4/BCD_modulo_3_util_vector_logic_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_5/BCD_modulo_3_util_vector_logic_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_1/BCD_modulo_3_util_vector_logic_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_2/BCD_modulo_3_util_vector_logic_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_3/BCD_modulo_3_util_vector_logic_4_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_4/BCD_modulo_3_util_vector_logic_4_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_5/BCD_modulo_3_util_vector_logic_4_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_6/BCD_modulo_3_util_vector_logic_4_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_6 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_6} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_0/BCD_modulo_3_util_vector_logic_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_10_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_10_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_1/BCD_modulo_3_util_vector_logic_10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_10_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_10_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_0/BCD_modulo_3_util_vector_logic_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_12_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_12_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_0/BCD_modulo_3_util_vector_logic_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_1/BCD_modulo_3_util_vector_logic_13_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_2/BCD_modulo_3_util_vector_logic_13_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_3/BCD_modulo_3_util_vector_logic_13_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_0/BCD_modulo_3_util_vector_logic_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_14_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_14_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_0/BCD_modulo_3_util_vector_logic_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_15_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_15_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_4/BCD_modulo_3_util_vector_logic_13_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_1/BCD_modulo_3_util_vector_logic_14_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_14_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_14_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_1/BCD_modulo_3_util_vector_logic_15_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_15_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_15_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_0/BCD_modulo_3_util_vector_logic_22_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_22_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_22_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_1/BCD_modulo_3_util_vector_logic_22_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_22_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_22_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_6/BCD_modulo_3_util_vector_logic_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_6 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_6} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_0/BCD_modulo_3_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_1_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_0/BCD_modulo_3_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_2_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_0/BCD_modulo_3_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_3_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_7/BCD_modulo_3_util_vector_logic_4_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_7 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_7} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_0/BCD_modulo_3_util_vector_logic_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_5_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_5_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_0/BCD_modulo_3_util_vector_logic_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_6_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_6_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_0/BCD_modulo_3_util_vector_logic_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_7_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_7_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_0/BCD_modulo_3_util_vector_logic_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_8_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_8_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_0/BCD_modulo_3_util_vector_logic_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_9_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_9_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_2/BCD_modulo_3_util_vector_logic_10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_10_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_10_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_0/BCD_modulo_3_util_vector_logic_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_11_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_11_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_1/BCD_modulo_3_util_vector_logic_12_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_12_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_12_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_5/BCD_modulo_3_util_vector_logic_13_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_2/BCD_modulo_3_util_vector_logic_14_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_14_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_14_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_2/BCD_modulo_3_util_vector_logic_15_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_15_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_15_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_0/BCD_modulo_3_util_vector_logic_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_16_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_16_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_0/BCD_modulo_3_util_vector_logic_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_17_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_17_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_0/BCD_modulo_3_util_vector_logic_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_18_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_18_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_0/BCD_modulo_3_util_vector_logic_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_19_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_19_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_0/BCD_modulo_3_util_vector_logic_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_20_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_20_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_0/BCD_modulo_3_util_vector_logic_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_21_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_21_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_2/BCD_modulo_3_util_vector_logic_22_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_22_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_22_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_0/BCD_modulo_3_util_vector_logic_23_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_23_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_23_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_7/BCD_modulo_3_util_vector_logic_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_7 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_7} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_8/BCD_modulo_3_util_vector_logic_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_8 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_8} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_9/BCD_modulo_3_util_vector_logic_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_9 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_9} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_10/BCD_modulo_3_util_vector_logic_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_10 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_10} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_8/BCD_modulo_3_util_vector_logic_4_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_8 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_8} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_9/BCD_modulo_3_util_vector_logic_4_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_9 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_9} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_10/BCD_modulo_3_util_vector_logic_4_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_10 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_10} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_11/BCD_modulo_3_util_vector_logic_4_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_11 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_11} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_12/BCD_modulo_3_util_vector_logic_4_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_12 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_12} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_13/BCD_modulo_3_util_vector_logic_4_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_13 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_13} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_14/BCD_modulo_3_util_vector_logic_4_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_14 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_14} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_15/BCD_modulo_3_util_vector_logic_4_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_15 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_15} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_16/BCD_modulo_3_util_vector_logic_4_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_16 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_16} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_7/BCD_modulo_3_util_vector_logic_13_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_7 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_7} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_8/BCD_modulo_3_util_vector_logic_13_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_8 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_8} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_17/BCD_modulo_3_util_vector_logic_4_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_17 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_17} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_1/BCD_modulo_3_util_vector_logic_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_5_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_5_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_1/BCD_modulo_3_util_vector_logic_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_7_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_7_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_3/BCD_modulo_3_util_vector_logic_15_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_15_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_15_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_1/BCD_modulo_3_util_vector_logic_16_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_16_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_16_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_1/BCD_modulo_3_util_vector_logic_17_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_17_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_17_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_4/BCD_modulo_3_util_vector_logic_15_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_15_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_15_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_2/BCD_modulo_3_util_vector_logic_16_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_16_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_16_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_2/BCD_modulo_3_util_vector_logic_17_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_17_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_17_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_9/BCD_modulo_3_util_vector_logic_13_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_9 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_9} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_3/BCD_modulo_3_util_vector_logic_14_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_14_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_14_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_11/BCD_modulo_3_util_vector_logic_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_11 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_11} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_1/BCD_modulo_3_util_vector_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_1_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_1/BCD_modulo_3_util_vector_logic_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_2_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_2_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_1/BCD_modulo_3_util_vector_logic_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_3_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_3_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_18/BCD_modulo_3_util_vector_logic_4_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_18 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_18} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_2/BCD_modulo_3_util_vector_logic_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_5_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_5_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_1/BCD_modulo_3_util_vector_logic_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_6_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_6_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_2/BCD_modulo_3_util_vector_logic_7_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_7_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_7_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_1/BCD_modulo_3_util_vector_logic_8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_8_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_8_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_1/BCD_modulo_3_util_vector_logic_9_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_9_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_9_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_3/BCD_modulo_3_util_vector_logic_10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_10_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_10_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_1/BCD_modulo_3_util_vector_logic_11_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_11_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_11_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_2/BCD_modulo_3_util_vector_logic_12_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_12_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_12_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_10/BCD_modulo_3_util_vector_logic_13_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_10 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_10} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_4/BCD_modulo_3_util_vector_logic_14_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_14_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_14_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_5/BCD_modulo_3_util_vector_logic_15_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_15_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_15_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_3/BCD_modulo_3_util_vector_logic_16_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_16_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_16_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_3/BCD_modulo_3_util_vector_logic_17_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_17_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_17_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_1/BCD_modulo_3_util_vector_logic_18_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_18_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_18_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_1/BCD_modulo_3_util_vector_logic_19_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_19_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_19_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_1/BCD_modulo_3_util_vector_logic_20_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_20_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_20_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_1/BCD_modulo_3_util_vector_logic_21_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_21_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_21_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_3/BCD_modulo_3_util_vector_logic_22_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_22_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_22_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_1/BCD_modulo_3_util_vector_logic_23_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_23_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_23_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_12/BCD_modulo_3_util_vector_logic_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_12 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_12} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_2/BCD_modulo_3_util_vector_logic_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_1_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_1_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_2/BCD_modulo_3_util_vector_logic_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_2_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_2_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_2/BCD_modulo_3_util_vector_logic_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_3_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_3_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_19/BCD_modulo_3_util_vector_logic_4_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_19 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_19} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_3/BCD_modulo_3_util_vector_logic_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_5_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_5_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_2/BCD_modulo_3_util_vector_logic_6_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_6_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_6_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_3/BCD_modulo_3_util_vector_logic_7_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_7_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_7_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_2/BCD_modulo_3_util_vector_logic_8_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_8_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_8_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_2/BCD_modulo_3_util_vector_logic_9_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_9_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_9_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_4/BCD_modulo_3_util_vector_logic_10_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_10_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_10_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_2/BCD_modulo_3_util_vector_logic_11_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_11_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_11_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_3/BCD_modulo_3_util_vector_logic_12_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_12_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_12_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_11/BCD_modulo_3_util_vector_logic_13_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_11 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_11} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_5/BCD_modulo_3_util_vector_logic_14_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_14_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_14_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_6/BCD_modulo_3_util_vector_logic_15_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_15_6 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_15_6} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_4/BCD_modulo_3_util_vector_logic_16_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_16_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_16_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_4/BCD_modulo_3_util_vector_logic_17_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_17_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_17_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_2/BCD_modulo_3_util_vector_logic_18_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_18_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_18_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_2/BCD_modulo_3_util_vector_logic_19_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_19_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_19_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_2/BCD_modulo_3_util_vector_logic_20_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_20_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_20_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_2/BCD_modulo_3_util_vector_logic_21_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_21_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_21_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_4/BCD_modulo_3_util_vector_logic_22_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_22_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_22_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_2/BCD_modulo_3_util_vector_logic_23_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_23_2 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_23_2} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_13/BCD_modulo_3_util_vector_logic_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_13 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_13} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_3/BCD_modulo_3_util_vector_logic_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_1_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_1_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_3/BCD_modulo_3_util_vector_logic_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_2_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_2_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_3/BCD_modulo_3_util_vector_logic_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_3_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_3_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_20/BCD_modulo_3_util_vector_logic_4_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_20 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_20} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_4/BCD_modulo_3_util_vector_logic_5_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_5_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_5_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_3/BCD_modulo_3_util_vector_logic_6_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_6_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_6_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_4/BCD_modulo_3_util_vector_logic_7_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_7_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_7_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_3/BCD_modulo_3_util_vector_logic_8_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_8_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_8_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_3/BCD_modulo_3_util_vector_logic_9_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_9_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_9_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_5/BCD_modulo_3_util_vector_logic_10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_10_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_10_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_3/BCD_modulo_3_util_vector_logic_11_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_11_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_11_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_4/BCD_modulo_3_util_vector_logic_12_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_12_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_12_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_12/BCD_modulo_3_util_vector_logic_13_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_12 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_12} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_6/BCD_modulo_3_util_vector_logic_14_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_14_6 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_14_6} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_7/BCD_modulo_3_util_vector_logic_15_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_15_7 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_15_7} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_5/BCD_modulo_3_util_vector_logic_16_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_16_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_16_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_5/BCD_modulo_3_util_vector_logic_17_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_17_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_17_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_3/BCD_modulo_3_util_vector_logic_18_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_18_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_18_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_3/BCD_modulo_3_util_vector_logic_19_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_19_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_19_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_3/BCD_modulo_3_util_vector_logic_20_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_20_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_20_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_3/BCD_modulo_3_util_vector_logic_21_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_21_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_21_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_5/BCD_modulo_3_util_vector_logic_22_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_22_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_22_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_3/BCD_modulo_3_util_vector_logic_23_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_23_3 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_23_3} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_24_0/BCD_modulo_3_util_vector_logic_24_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_24_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_24_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_25_0/BCD_modulo_3_util_vector_logic_25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_25_0 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_25_0} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_14/BCD_modulo_3_util_vector_logic_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_14 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_14} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_1_4/BCD_modulo_3_util_vector_logic_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_1_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_1_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_2_4/BCD_modulo_3_util_vector_logic_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_2_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_2_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_3_4/BCD_modulo_3_util_vector_logic_3_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_3_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_3_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_4_21/BCD_modulo_3_util_vector_logic_4_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_4_21 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_4_21} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_5_5/BCD_modulo_3_util_vector_logic_5_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_5_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_5_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_6_4/BCD_modulo_3_util_vector_logic_6_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_6_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_6_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_7_5/BCD_modulo_3_util_vector_logic_7_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_7_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_7_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_8_4/BCD_modulo_3_util_vector_logic_8_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_8_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_8_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_9_4/BCD_modulo_3_util_vector_logic_9_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_9_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_9_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_10_6/BCD_modulo_3_util_vector_logic_10_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_10_6 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_10_6} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_11_4/BCD_modulo_3_util_vector_logic_11_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_11_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_11_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_12_5/BCD_modulo_3_util_vector_logic_12_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_12_5 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_12_5} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_13_13/BCD_modulo_3_util_vector_logic_13_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_13_13 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_13_13} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_14_7/BCD_modulo_3_util_vector_logic_14_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_14_7 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_14_7} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_15_8/BCD_modulo_3_util_vector_logic_15_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_15_8 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_15_8} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_16_6/BCD_modulo_3_util_vector_logic_16_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_16_6 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_16_6} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_17_6/BCD_modulo_3_util_vector_logic_17_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_17_6 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_17_6} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_18_4/BCD_modulo_3_util_vector_logic_18_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_18_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_18_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_19_4/BCD_modulo_3_util_vector_logic_19_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_19_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_19_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_20_4/BCD_modulo_3_util_vector_logic_20_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_20_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_20_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_21_4/BCD_modulo_3_util_vector_logic_21_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_21_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_21_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_22_6/BCD_modulo_3_util_vector_logic_22_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_22_6 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_22_6} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_23_4/BCD_modulo_3_util_vector_logic_23_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_23_4 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_23_4} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_24_1/BCD_modulo_3_util_vector_logic_24_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_24_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_24_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_25_1/BCD_modulo_3_util_vector_logic_25_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_25_1 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_25_1} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_15/BCD_modulo_3_util_vector_logic_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_15 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_15} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_16/BCD_modulo_3_util_vector_logic_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_16 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_16} -quiet] -quiet

# IP: bd/BCD_modulo_3/ip/BCD_modulo_3_util_vector_logic_0_17/BCD_modulo_3_util_vector_logic_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BCD_modulo_3_util_vector_logic_0_17 || ORIG_REF_NAME==BCD_modulo_3_util_vector_logic_0_17} -quiet] -quiet

# XDC: bd/BCD_modulo_3/BCD_modulo_3_ooc.xdc
